### ISSUE TITLE
TypeError: Value passed to parameter 'shape' has DataType float32 not in list of allowed values: int32, int64

### ISSUE THREAD

**Issue by gauravgola96** [oswaldoludwig/Seq2seq-Chatbot-for-Keras#17]
I am using python 3.
error in this line
--> 155 out = Dense(dictionary_size/2, activation="relu", name='relu-activation')(merge_layer)

**Comment by oswaldoludwig** [comment]
Hi, this project uses Python 2.7.6, Ubuntu 14.04.3 LTS, Theano 0.9.0, and Keras 2.0.4.

**Comment by gauravgola96** [comment]
int(dictionary_size/2) 
this worked for me.

**Comment by oswaldoludwig** [comment]
This makes sense, especially if the dictionary size is not an even number.

**Comment by gauravgola96** [comment]
can you provide me the data for question answer .

**Comment by oswaldoludwig** [comment]
If you mean the training data that I used, it is here: https://www.dropbox.com/sh/o0rze9dulwmon8b/AAA6g6QoKM8hBEHGst6W4JGDa?dl=0

**Comment by gauravgola96** [comment]
this what is happening ...
any solution for this




Starting the model...

 
 
 
    CHAT:     
 

computer: hi ! please type your name.

user: hh
computer: hi , hh ! My name is john.

user: benjamin
computer:  yeah , but my favorite one is hard to find .     (with probability of 0.000973)
user: will benjamin
computer:  yeah , but my favorite one is hard to find .     (with probability of 0.000973)
user: exit
computer:  yeah , but my favorite one is hard to find .     (with probability of 0.000973)

**Comment by oswaldoludwig** [comment]
It seems like you keep entering your name when you should start a conversation.

**Comment by gauravgola96** [comment]
Starting the model...

 
 
I guess No!! 


    CHAT:     
 

computer: hi ! please type your name.

user: how are you?
computer: hi , how are you? ! My name is john
