### ISSUE TITLE
Getting AttributeError:int cannot find replace.

### ISSUE THREAD

**Issue by Anoopparjanya** [oswaldoludwig/Seq2seq-Chatbot-for-Keras#19]
@oswaldoludwig ,
![split_qa](https://user-images.githubusercontent.com/39297410/41330673-b4f9a25e-6e89-11e8-924f-4c2518194796.png)
I'm trying to execute split_qa.py.When i run the file,it is throwing me the above error.
I'm not knowing where this raw_word is converting into int.Tried many combinations,but its not working.
Could you please help me out in this scenario?

Please find the attached.

**Comment by oswaldoludwig** [comment]
You introduced an error when you modified the script in this line:
`with open(r'C:\Users\...`

**Comment by Anoopparjanya** [comment]
How to load my data?
When i give the file name in open('data','r'),it is throwing directory is not found error.
When i give the file path(open('file path'),it is throwing syntax error?
I'm in learning stage,do help me @oswaldoludwig.

**Comment by oswaldoludwig** [comment]
Just use `text = open('C:\Users\...\data.txt', 'r')`.

**Comment by Anoopparjanya** [comment]
Thanks @oswaldoludwig It worked now!! 
But now im facing a new problem.


Using Theano backend.
WARNING (theano.configdefaults): install mkl with `conda install mkl-service`: No module named 'mkl'
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Found 400000 word vectors.

Warning (from warnings module):
  File "C:\Users\Anoop\Documents\Seq2seq-Chatbot-for-Keras-master\train_bot.py", line 101
    LSTM_encoder = LSTM(sentence_embedding_size, init= 'lecun_uniform')
UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(300, kernel_initializer="lecun_uniform")`

Warning (from warnings module):
  File "C:\Users\Anoop\Documents\Seq2seq-Chatbot-for-Keras-master\train_bot.py", line 102
    LSTM_decoder = LSTM(sentence_embedding_size, init= 'lecun_uniform')
UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(300, kernel_initializer="lecun_uniform")`
Traceback (most recent call last):
  File "C:\Users\Anoop\Documents\Seq2seq-Chatbot-for-Keras-master\train_bot.py", line 113, in <module>
    merge_layer = merge([context_embedding, answer_embedding], mode='concat', concat_axis=1)
TypeError: 'module' object is not callable

How to solve this? Why this is happening?

Thanks in Advance!!
