### ISSUE TITLE
enhancement - investigate supplying conda environment.yml / requirements.txt with exported python 2.7.6 dependencies

### ISSUE THREAD

**Issue by johndpope** [oswaldoludwig/Seq2seq-Chatbot-for-Keras#21]
see here for sample environment
https://github.com/johndpope/dev_env/tree/master/conda

this is a sample conda file / rather like requirements.txt / it also encapsulates pip dependencies
https://github.com/johndpope/dev_env/blob/master/conda/tensorflow-gpu.yml

with this file  / environment on any install linux / windows etc 
 - python 2 will be forced along with all (legacy) dependencies. 

N.B. - to upgrade codebase to python3 is not too bad - just use 
`2to3 *.py -w `

**Comment by johndpope** [comment]
like this
https://github.com/johndpope/summerschool/tree/master/assignment/classifier



### Environment and Imports

You can either use the environment.yml file to set up a virtual environment or install the required packages. All experiments and tests can be run inside the required notebooks.

Use the environment.yml file by running:

**conda env create -f environment.yml**

```environment.yml

name: jsalt
channels:
    - anaconda
    - conda-forge
dependencies:
    - jupyter
    - python=3.6
    - tensorflow=1.8.0
    - numpy=1.14.5
    - nltk=3.2.5
    - scikit-learn=0.19.1
    - pandas=0.20.3
    - bokeh=0.12.13
    - pip:
        - graphviz
        - wget
       

```

**Comment by blancNoir** [comment]
A Dockerfile would be appreciated too, or image on dockerhub.
