### ISSUE TITLE
where did you proposes a persona embedding?

### ISSUE THREAD

**Issue by cczka** [oswaldoludwig/Seq2seq-Chatbot-for-Keras#29]
Hello, the paper said "This work proposes a persona embedding that  permits the incorporation of background facts for user profiles, person-specific language behavior, and interaction style.". So, I'm curious that have you ever proposed a persona embedding?

**Comment by oswaldoludwig** [comment]
This is a space for issues with repo, not paper review. The text you refer to is an excerpt from the State-of-the-art section of my paper, where I refer to the paper [18], which is where you can find this content. You can find the title of paper [18] at the end of this document, in the section references.

**Comment by cczka** [comment]
yeah I already knew it, but did you utlize a persona embedding in your repo?
