### ISSUE TITLE
how a new vocabulary file can be generated?

### ISSUE THREAD

**Issue by Asrix-AI** [oswaldoludwig/Seq2seq-Chatbot-for-Keras#30]
can you please explain how you generated your vocabulary file?

**Comment by oswaldoludwig** [comment]
https://github.com/oswaldoludwig/Seq2seq-Chatbot-for-Keras/issues/4

**Comment by oswaldoludwig** [comment]
Just be careful of the index of the special symbols, BOS and EOS, their positions/indexes are fixed in the dictionary.

**Comment by Asrix-AI** [comment]
Thank you.

**Comment by Asrix-AI** [comment]
can you please explain why this error is occurring?
Traceback (most recent call last):
  File "conversation.py", line 215, in <module>
    Q = tokenize(query)
  File "conversation.py", line 117, in tokenize
    X = np.asarray([word_to_index[w] for w in tokenized_sentences])
  File "conversation.py", line 117, in <listcomp>
    X = np.asarray([word_to_index[w] for w in tokenized_sentences])
KeyError: 'something'

**Comment by oswaldoludwig** [comment]
It looks like your dictionary doesn't have the key "something". You must use a preprocessing function that exists somewhere in my code that replaces all non-dictionary words with a special token, such as UNK.
