### ISSUE TITLE
SyntaxError in conversation.py

### ISSUE THREAD

**Issue by manabuo** [oswaldoludwig/Seq2seq-Chatbot-for-Keras#6]
What is the Python version for this project? Because I have systax error in conversation.py as follows.

> 

  File "conversation.py", line 95
    if raw_word[-1] <>  '!' and raw_word[-1] <> '?' and raw_word[-1] <> '.' and raw_word[-2:] <>  '! ' and raw_word[-2:] <> '? ' and raw_word[-2:] <> '. ':

**Comment by oswaldoludwig** [comment]
Python 2.x

**Comment by oswaldoludwig** [comment]
... with Theano 0.9.0 and Keras 1.0.4.

**Comment by oswaldoludwig** [comment]
This project was done in Linux, Python 2.x, Theano 0.9.0, and Keras 1.0.4. The use of another configuration may require some minor adaptations.

**Comment by mohannadrateb** [comment]
replace "<>" by != , this should make it work n python 3.x
