### ISSUE TITLE
"w" in get_train_data.py

### ISSUE THREAD

**Issue by fsfeng** [oswaldoludwig/Seq2seq-Chatbot-for-Keras#7]
Hi, in lines 88 & 91 of `get_train_data.py`, it should be "wb" not "w" when writing to Pickle as it will otherwise cause write error.

**Comment by oswaldoludwig** [comment]
In case you are using Windows: https://stackoverflow.com/questions/15750660/python-file-io-w-vs-wb

**Comment by oswaldoludwig** [comment]
Thanks for this information that is useful for all Windows users. This project was done in Linux, Python 2.x, Theano 0.9.0, and Keras 1.0.4. The use of another configuration may require some minor adaptations.
