### ISSUE TITLE
Weights loading fails

### ISSUE THREAD

**Issue by EgorGumin** [oswaldoludwig/Seq2seq-Chatbot-for-Keras#8]
Hi! Trying to launch your example, but facing an error with loading weights:

```
Traceback (most recent call last):
  File "conversation.py", line 160, in <module>
    model.load_weights(weights_file)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2367, 
in load_weights  ' elements.')
Exception: Layer #3 (named "Encode answer up to the current token" in the current model) 
was found to correspond to layer lstm_1 in the save file. 
However the new layer Encode answer up to the current token expects 12 weights, 
but the saved weights have 3 elements.
```

**Comment by oswaldoludwig** [comment]
Are you using Theano backend?  "This project was done in Linux, Python 2.x, Theano 0.9.0, and Keras 1.0.4. The use of another configuration may require some minor adaptations".

**Comment by EgorGumin** [comment]
Yes, I'm using Python 2.7.12, Theano 0.9.0 and Keras 1.0.4

**Comment by oswaldoludwig** [comment]
if you keep these parameters the code should run smoothly:
word_embedding_size = 100
sentence_embedding_size = 300
dictionary_size = 7000
maxlen_input = 50

**Comment by EgorGumin** [comment]
I did not modified your `conversation.py` example, so I have exactly the same params, but the code fails with an error mentioned above. I think an error might be caused by incorrect weights file, but I'm not sure

**Comment by oswaldoludwig** [comment]
Can you check the new model conversation_discriminator.py?

**Comment by EgorGumin** [comment]
The same result
```
Using Theano backend.
Starting the model...

CHAT:

computer: hi ! please type your name.
user: Egor
computer: hi , Egor ! My name is john.
user: Hi

Traceback (most recent call last):
  File "conversation_discriminator.py", line 279, in <module>
    model.load_weights(weights_file)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2367, 
in load_weights ' elements.')
Exception: Layer #3 (named "Encode answer up to the current token" in the current model) 
was found to correspond to layer lstm_1 in the save file. However the new layer 
Encode answer up to the current token expects 12 weights, but the saved weights have 3 elements.
```

**Comment by oswaldoludwig** [comment]
Now I have no clue, I have to think about later. If you find a workaround for your issue, let us know, you can help other users cope with similar issues. Otherwise, you can delete the weight file and train the model from the scratch (see the readme file). Using GPU you will have a chatbot able to chat with you in less than one hour of training.

**Comment by ascherbakhov** [comment]
I have this issue too. Ubuntu 16.04, Python 2.7, Keras 1.0.4, Theano 0.9.0.  Can you please rerun conversation.py with your weights file on your machine?
Also i have import error on from keras.utils import plot_model.
As I know, plot_model function was moved to other module and  in keras 1.0.4 "plot" function was in keras.utils.visualize_util.

I'm afraid, we have different keras versions.

**Comment by oswaldoludwig** [comment]
The script can run, but now I've received some warnings from Keras, I'll check this out later:
 
CHAT:     
 
computer: hi ! please type your name.

user: oswaldo
computer: hi , oswaldo ! My name is john.

user: Nice to meet you! How are you?
conversation_discriminator.py:143: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(300, kernel_initializer="lecun_uniform", name="encoder discriminator")`
  LSTM_encoder_discriminator = LSTM(sentence_embedding_size, init= 'lecun_uniform', name = 'encoder discriminator')
conversation_discriminator.py:145: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(300, kernel_initializer="lecun_uniform", name="decoder discriminator")`
  LSTM_decoder_discriminator = LSTM(sentence_embedding_size, init= 'lecun_uniform', name = 'decoder discriminator')
conversation_discriminator.py:151: UserWarning: The `merge` function is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  loss = merge([context_embedding_discriminator, answer_embedding_discriminator, input_current_token], mode='concat', concat_axis=1, name = 'concatenation discriminator')
conversation_discriminator.py:154: UserWarning: Update your `Model` call to the Keras 2 API: `Model(outputs=[sigmoid.0..., inputs=[/input co...)`
  model_discrim = Model(input=[input_context, input_answer, input_current_token], output = [loss])

computer:  i am fine , thanks ! 
user: What are you doing now? Are you busy?

computer:  i am going to the . 
user: Where are you going?

computer:  i am going to the station . 
user: Are you going to travel?

computer:  no , i am not . i am going to the bank . 
user:

**Comment by oswaldoludwig** [comment]
I updated the files conversation.py and conversation_discriminator.py. Now both codes work without problems and no warnings on my machine with Keras 2.0.4. Please let me know if this has solved your problem (remember to install Keras 2.0.4).
