### ISSUE TITLE
Valid Scope name 

### ISSUE THREAD

**Issue by mohannadrateb** [oswaldoludwig/Seq2seq-Chatbot-for-Keras#9]
When trying to run conversation.py this error pops up 

 File "/Users/Mohannad/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2908, in name_scope
    raise ValueError("'%s' is not a valid scope name" % name)
ValueError: 'the context text' is not a valid scope name

Any idea what is this or how t solve it ?
Thanks

**Comment by oswaldoludwig** [comment]
I don't have this problem, we probably have different versions of Keras. I also saw that you have Python 3.6 and this code was developed in Python 2.7. Either way, you can remove all the parameters **name**, e.g. **name='Encode context'**. These parameters are important only to generate the model figure (see the readme file). In this case you can also remove the line: **plot_model(model, to_file='model_graph.png')**.

**Comment by mohannadrateb** [comment]
yes, removing  the name parameter stopped this error from popping up !!
Thanks a lot !!
